In [3]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv(r"C:\Users\USER\Documents\Project\Amazon_data.csv")

In [7]:
df.head()

,Order ID,Order Date,Ship Date,EmailID,Geography,Category,Product Name,Sales,Quantity,Profit
0,CA-2013-138688,13-06-2013,17-06-2013,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2.0,6.87
1,CA-2011-115812,09-06-2011,14-06-2011,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7.0,14.17
2,CA-2011-115812,09-06-2011,14-06-2011,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,Newell 322,7.28,4.0,1.97
3,CA-2011-115812,09-06-2011,14-06-2011,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,Mitel 5320 IP Phone VoIP phone,907.15,4.0,90.72
4,CA-2011-115812,09-06-2011,14-06-2011,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,DXL Angle-View Binders with Locking Rings by S...,18.50,3.0,5.78

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      3203 non-null   str
 1   Order Date    3203 non-null   str
 2   Ship Date     3203 non-null   str
 3   EmailID       3203 non-null   str
 4   Geography     3203 non-null   str
 5   Category      3203 non-null   str
 6   Product Name  3203 non-null   str
 7   Sales         3203 non-null   float64
 8   Quantity      3203 non-null   float64
 9   Profit        3203 non-null   float64
dtypes: float64(3), str(7)
memory usage: 250.4 KB

In [9]:
df.describe()

              Sales     Quantity       Profit
count   3203.000000  3203.000000  3203.000000
mean     226.493266     3.828910    33.849138
std      524.876911     2.260947   174.109155
min        0.990000     1.000000 -3399.980000
25%       19.440000     2.000000     3.850000
50%       60.840000     3.000000    11.170000
75%      215.810000     5.000000    33.000000
max    13999.960000    14.000000  6719.980000

In [10]:
df.isnull().sum()

Order ID        0
Order Date      0
Ship Date       0
EmailID         0
Geography       0
Category        0
Product Name    0
Sales           0
Quantity        0
Profit          0
dtype: int64

In [12]:
df = df.dropna()

In [13]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'EmailID', 'Geography',
       'Category', 'Product Name', 'Sales', 'Quantity', 'Profit'],
      dtype='str')

In [14]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [15]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'emailid', 'geography',
       'category', 'product_name', 'sales', 'quantity', 'profit'],
      dtype='str')

In [25]:
df['order_date'] = pd.to_datetime(df['order_date'],
    errors='coerce',  
    dayfirst=True,
    format='%d/%m/%Y'
)

In [26]:
df['ship_date'] = pd.to_datetime(df['ship_date'],
    errors='coerce',
    dayfirst=True,
    format='%d/%m/%Y'  
)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      3203 non-null   str
 1   order_date    0 non-null      datetime64[s]
 2   ship_date     3203 non-null   datetime64[us]
 3   emailid       3203 non-null   str
 4   geography     3203 non-null   str
 5   category      3203 non-null   str
 6   product_name  3203 non-null   str
 7   sales         3203 non-null   float64
 8   quantity      3203 non-null   float64
 9   profit        3203 non-null   float64
dtypes: datetime64[s](1), datetime64[us](1), float64(3), str(5)
memory usage: 250.4 KB

In [29]:
df['profit_margin']=df['profit']/df['sales']

In [30]:
df.head()

,order_id,order_date,ship_date,emailid,geography,category,product_name,sales,quantity,profit,profit_margin
0,CA-2013-138688,NaT,2013-06-17,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2.0,6.87,0.469904
1,CA-2011-115812,NaT,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7.0,14.17,0.290012
2,CA-2011-115812,NaT,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,Newell 322,7.28,4.0,1.97,0.270604
3,CA-2011-115812,NaT,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,Mitel 5320 IP Phone VoIP phone,907.15,4.0,90.72,0.100006
4,CA-2011-115812,NaT,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,DXL Angle-View Binders with Locking Rings by S...,18.50,3.0,5.78,0.312432

In [31]:
df.to_csv(r"C:\Users\USER\Documents\Project\cleaned_amazon_sales_data.csv", index=False)